site_name: Redes Neurais
site_author: Daniel Marco Djanikian
site_url: https://danielmarcod.github.io/redesneurais/
repo_url: https://github.com/DanielMarcoD/redesneurais
repo_name: DanielMarcoD/redesneurais
exclude_docs: |
  **/__pycache__/**

theme:
  name: material
  language: pt-BR
  features:
    - content.code.copy
    - navigation.top

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      base_path: .
  - pymdownx.superfences

plugins:
  - search

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Início: index.md
  - Exercícios:
      - Dados: exercises/data/index.md
      - Perceptron: exercises/perceptron/index.md
  - Projects:
      - EDA: project/eda/index.md
